# Generated by Django 5.0.2 on 2024-04-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HydroApps', '0001_initial'),
        ('my_auth', '0002_account_expiration_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionClass',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Permission class',
                'verbose_name_plural': 'Permission classes',
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_tester',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HydroApps.app')),
                ('permission_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.permissionclass')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table_comment': 'Possible Permissions for each app.',
                'unique_together': {('app', 'permission_class')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.ManyToManyField(blank=True, default=None, help_text='The permissions the user has.', to='my_auth.permission'),
        ),
    ]
