# Generated by Django 5.0.2 on 2024-04-18 12:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_permissionclass_remove_account_is_tester_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPermission',
            fields=[
                ('token', models.CharField(default='PGfeXtuEf6w49sbvUhYDb8Y8BxKu9eLjaqbhkx3mFMUftxrZXvpCLmhayk95bPkcAQ8qaaLaYHuqP8eLzhQJrUdNwAZceTKQubcj', max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=300)),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2024, 5, 18, 12, 25, 25, 109601, tzinfo=datetime.timezone.utc))),
                ('permissions', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='my_auth.permission')),
            ],
            options={
                'verbose_name': 'Token Permission',
                'verbose_name_plural': 'Token Permission',
                'db_table_comment': 'Permissions granted via a token to be used for a limited time to access the Hydro-Apps.',
            },
        ),
    ]
