# based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Django.gitlab-ci.yml

variables:
    HYDROAPPS_SECRET_KEY: 'very_long_secret_key123'
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust
    HYDROAPPS_DB_HOST: hydroapps
    HYDROAPPS_DB_DATABASE: hydroapps
    WEATHERDB_DB_HOST: weatherdb
    WEATHERDB_DB_DATABASE: weatherdb
    WEATHERDB_DB_PORT: $POSTGRES_PORT
    WEATHERDB_DB_USER: $POSTGRES_USER
    WEATHERDB_DB_PASSWORD: $POSTGRES_PASSWORD
    WEATHERDB_LOGGING_HANDLER: console
    WEATHERDB_LOGGING_LEVEL: DEBUG

workflow:
  auto_cancel:
    on_new_commit: interruptible

default:
    image: python:3.10
    services:
        - name: postgis/postgis
          alias: hydroapps
          variables:
              POSTGRES_DB: $HYDROAPPS_DB_DATABASE
        - name: postgis/postgis
          alias: weatherdb
          variables:
              POSTGRES_DB: $WEATHERDB_DB_DATABASE
    before_script:
        - apt update && apt install nodejs npm libgdal-dev -y
        - pip3 install -r requirements.txt --root-user-action=ignore
        - weatherdb create-db-schema
    cache:
        paths:
        - ~/.cache/pip/

django-tests:
    stage: test
    tags:
        - docker
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: $CI_COMMIT_BRANCH == "master"
    script:
        - cp secretSettings_HydroApps.py.test secretSettings_HydroApps.py
        - mkdir static_data
        - cd front-end && npm ci && npm run build && cd ../
        - python3 manage.py migrate
        - python3 manage.py collectstatic --noinput
        - python3 manage.py test my_auth weatherdb RheiKlim kombstra sri_bw sfi_demo
    interruptible: true