# based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Django.gitlab-ci.yml

variables:
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust

default:
    image: python:3.10
    services:
        - postgres:latest
    before_script:
        - apt -y update
        - python --version
        - apt -y install apt-utils
        - apt -y install net-tools
        - apt -y install git
        - apt -y install postgresql-client
        - apt -y install libgdal-dev
        - apt -y upgrade
        - pip3 install -r requirements.txt
    cache:
        paths:
        - ~/.cache/pip/

django-tests:
    stage: test
    tags:
        - docker
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
    script:
        # The POSTGRES user only gets permissions for POSTGRES_DB, so Django can't create a test database.
        - export PGPASSWORD=$POSTGRES_PASSWORD
        - echo "CREATE DATABASE weatherdb OWNER '${POSTGRES_USER}'; \
                GRANT ALL on *.* to '${POSTGRES_USER}';" |
                psql -U $POSTGRES_USER -h "postgres" -d "$POSTGRES_DB"
        - cp secretSettings_HydroApps.py.test secretSettings_HydroApps.py
        - cp secretSettings_HydroApps.py.test secretSettings_weatherDB.py
        - python3 manage.py migrate
        - python3 manage.py test my_auth weatherdb asgII kombstra sri_bw
