# based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Django.gitlab-ci.yml

variables:
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust

default:
    image: ubuntu:20.04
    services:
        - postgresql:14.0
    before_script:
        - apt -y update
        - apt -y install apt-utils
        - apt -y install net-tools python3.8 python3-pip libmysqlclient-dev
        - apt -y upgrade
        - pip3 install -r requirements.txt
    cache:
        paths:
        - ~/.cache/pip/

django-tests:
  stage: test
  script:
    # The POSTGRES user only gets permissions for POSTGRES_DB, so Django can't create a test database.
    - echo "GRANT ALL on *.* to '${POSTGRES_USER}';"| psql -u postgres -c
    - cp secretSettings_HydroApps.py.test secretSettings_HydroApps.py
    - python3 manage.py test my_auth weatherdb asgII kombstra sri_bw
