FROM python:3.12-slim

RUN apt-get update && \
    apt-get upgrade -yqq &&\
    pip install -U pip pipenv uv &&\
    apt-get install -y nodejs npm libgdal-dev &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /app