# Generated by Django 4.2 on 2023-11-15 15:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.gis.gdal import SpatialReference
from django.contrib.gis.utils.srs import add_srs_entry
from pathlib import Path

def add_radolan_srs(*args, **kwargs):
    # combined spatialreference.org with DWD .prj file of radolan shape
    # siource: https://www.spatialreference.org/ref/sr-org/7019/
    with open(Path(__file__).parents[1] / "lib" / "radolan.prj", "r") as f:
        wkt_str = f.read()
    srs = SpatialReference(wkt_str, srs_type="wkt")
    add_srs_entry(srs, auth_name="SR-ORG", auth_srid=97019)

def remove_radolan_srs(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_radolan_srs,
            remove_radolan_srs
        ),
        migrations.CreateModel(
            name='kombstraPolygons',
            fields=[
                ('grid_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'kombstra_polygons',
            },
        ),
        migrations.CreateModel(
            name='kombstraData',
            fields=[
                ('data_id', models.BigAutoField(help_text='ID of the event', primary_key=True, serialize=False)),
                ('duration', models.IntegerField(help_text='Duration class of the event (Dauerstufe) in minutes')),
                ('pval', models.FloatField(help_text='Precipitation amount of the event in mm')),
                ('sri', models.IntegerField(help_text='Starkregen-Index (SRI) of the event')),
                ('date', models.DateField(help_text='Date of the event')),
                ('event_rank', models.IntegerField(help_text='Rank of the event in the grid-cell')),
                ('percentile', models.IntegerField(help_text='Percentile of the event in the grid-cell')),
                ('grid_id', models.ForeignKey(db_column='grid_id', help_text='ID to link to the Grid-Cell', on_delete=django.db.models.deletion.DO_NOTHING, to='kombstra.kombstrapolygons')),
            ],
            options={
                'db_table': 'kombstra_data',
            },
        ),
        migrations.CreateModel(
            name='KombStRAGrid',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=97019)),
            ],
            options={
                'db_table': 'kombstra_grid',
            },
        )
    ]
