# Generated by Django 4.2 on 2023-11-20 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.gdal import SpatialReference
from django.contrib.gis.utils.srs import add_srs_entry
from pathlib import Path

def add_radolan_srs(*args, **kwargs):
    # combined spatialreference.org with DWD .prj file of radolan shape
    # siource: https://www.spatialreference.org/ref/sr-org/7019/
    with open(Path(__file__).parents[1] / "lib" / "radolan.prj", "r") as f:
        wkt_str = f.read()
    srs = SpatialReference(wkt_str, srs_type="wkt")
    add_srs_entry(srs, auth_name="SR-ORG", auth_srid=97019)

def remove_radolan_srs(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kombstra', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_radolan_srs,
            remove_radolan_srs
        ),
        migrations.CreateModel(
            name='KombStRAGrids',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('percentile', models.IntegerField(db_index=True)),
                ('event_rank', models.IntegerField(db_index=True)),
                ('para', models.CharField(choices=[('DUR', 'Duration'), ('PVAL', 'Precipitation amount'), ('SRI', 'Starkregen-Index'), ('YEAR', 'Year'), ('MONTH', 'Month'), ('FEvNR', 'Event rank')], db_index=True, max_length=5)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=97019)),
            ],
            options={
                'db_table': 'kombstra_grids',
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE kombstra_grids_rid_seq MINVALUE 1;
                ALTER TABLE public.kombstra_grids ALTER rid SET DEFAULT nextval('kombstra_grids_rid_seq');
                ALTER SEQUENCE kombstra_grids_rid_seq OWNED BY kombstra_grids.rid;""",
            reverse_sql="DROP SEQUENCE IF EXISTS kombstra_grids_rid_seq CASCADE;")
    ]
