# Generated by Django 5.1.6 on 2025-08-14 10:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kombstra', '0003_create_dataspans_remove_sri_max_events'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE kombstra_polygons
            ALTER COLUMN geometry TYPE geometry(Polygon, 4326)
            USING ST_SetSRID(geometry, 4326);
            """,
            reverse_sql="""
            ALTER TABLE kombstra_polygons
            ALTER COLUMN geometry TYPE geometry(Polygon, 97019)
            USING ST_SetSRID(geometry, 97019);
            """
        ),
        migrations.AlterField(
            model_name='kombstrapolygons',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
