# Generated by Django 5.2.6 on 2025-10-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kombstra', '0005_optimize_dataspans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kombstradata',
            name='grid_id',
            field=models.ForeignKey(db_column='grid_id', help_text='ID to link to the Grid-Cell', on_delete=django.db.models.deletion.CASCADE, to='kombstra.kombstrapolygons'),
        ),
    ]
