# Generated by Max on 2025-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kombstra', '0006_alter_kombstradata_grid_id'),
    ]

    operations = [
        # optimize kombstra_data_spans view to not run into memory issues
        migrations.RunSQL(
            """DROP MATERIALIZED VIEW IF EXISTS kombstra_data_spans;
            CREATE MATERIALIZED VIEW kombstra_data_spans AS (
                WITH
                    -- Pre-calculate basic stats to avoid multiple scans
                    basic_stats AS (
                        SELECT
                            EXTRACT(year FROM min(date))::int AS min_year,
                            EXTRACT(YEAR FROM max(date))::int AS max_year,
                            max(event_rank)::int AS max_rank,
	                        max(pval) AS max_pval
                        FROM kombstra_data
                    ),
                    -- group multiple events on the same day per grid cell
                    max_sri_per_date_and_grid AS (
                        SELECT grid_id, date, max(sri) AS max_sri
                        FROM kombstra_data
                        GROUP BY grid_id, date
                    ),
                    -- Calculate events per SRI level more efficiently
                    nevents_per_grid_and_sri_level AS (
                        SELECT
                            msdg.grid_id,
                            sl.sri_level,
                            count(*) AS nevents
                        FROM max_sri_per_date_and_grid msdg
                        CROSS JOIN (SELECT generate_series(0,12) AS sri_level) AS sl
                        WHERE msdg.max_sri >= sl.sri_level
                        GROUP BY msdg.grid_id, sl.sri_level
                    ),
                    nevents_per_sri_level AS (
                        SELECT ngs.sri_level, max(nevents) AS nevents
                        FROM nevents_per_grid_and_sri_level ngs
                        GROUP BY ngs.sri_level ),
                    -- Find max events per SRI level
                    sri_max_nevents AS (
                        SELECT
                            json_objectagg(sri_level:nevents)::text AS max_nevents
                        FROM nevents_per_sri_level
                    )
                    SELECT
                        1 as id, -- dummy id
                        basic_stats.min_year,
                        basic_stats.max_year,
                        basic_stats.max_rank,
                        basic_stats.max_pval,
                        sri_max_nevents.max_nevents
                    FROM basic_stats, sri_max_nevents
                );
            """,
            """DROP MATERIALIZED VIEW IF EXISTS kombstra_data_spans;
            CREATE MATERIALIZED VIEW kombstra_data_spans AS (
                WITH
                    -- Pre-calculate basic stats to avoid multiple scans
                    basic_stats AS (
                        SELECT
                            EXTRACT(year FROM min(date))::int AS min_year,
                            EXTRACT(YEAR FROM max(date))::int AS max_year,
                            max(event_rank)::int AS max_rank
                        FROM kombstra_data
                    ),
                    -- group multiple events on the same day per grid cell
                    max_sri_per_date_and_grid AS (
                        SELECT grid_id, date, max(sri) AS max_sri
                        FROM kombstra_data
                        GROUP BY grid_id, date
                    ),
                    -- Calculate events per SRI level more efficiently
                    nevents_per_grid_and_sri_level AS (
                        SELECT
                            msdg.grid_id,
                            sl.sri_level,
                            count(*) AS nevents
                        FROM max_sri_per_date_and_grid msdg
                        CROSS JOIN (SELECT generate_series(0,12) AS sri_level) AS sl
                        WHERE msdg.max_sri >= sl.sri_level
                        GROUP BY msdg.grid_id, sl.sri_level
                    ),
                    nevents_per_sri_level AS (
                        SELECT ngs.sri_level, max(nevents) AS nevents
                        FROM nevents_per_grid_and_sri_level ngs
                        GROUP BY ngs.sri_level ),
                    -- Find max events per SRI level
                    sri_max_nevents AS (
                        SELECT
                            json_objectagg(sri_level:nevents)::text AS max_nevents
                        FROM nevents_per_sri_level
                    )
                    SELECT
                        1 as id, -- dummy id
                        basic_stats.min_year,
                        basic_stats.max_year,
                        basic_stats.max_rank,
                        sri_max_nevents.max_nevents
                    FROM basic_stats, sri_max_nevents
                );
            """,
            state_operations=[
                migrations.AddField(
                    model_name='kombstradataspans',
                    name='max_pval',
                    field=models.FloatField(help_text='Maximum Pprecipitation value of all the events'),
                )
            ]
        ),
    ]
