# Generated by Django 5.0.2 on 2024-10-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RheiKlim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metan',
            table='rheiklim_station_meta',
        ),
    ]
