# Generated by Django 5.1.6 on 2025-07-14 10:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNote',
            fields=[
                ('uniqueId', models.CharField(help_text='Unique ID for the note, e.g., UUID or similar', max_length=52, primary_key=True, serialize=False, unique=True)),
                ('details', models.TextField(help_text='Details of the note, e.g., description or comments')),
                ('lastModified', models.DateTimeField(help_text='Last modified timestamp')),
            ],
            options={
                'verbose_name': 'Location Note',
                'verbose_name_plural': 'Location Notes',
                'db_table': 'internal_aquarius_location_note',
            },
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('uniqueId', models.CharField(help_text='Unique ID for the tag, e.g., UUID or similar', max_length=52, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Location Tag',
                'verbose_name_plural': 'Location Tags',
                'db_table': 'internal_aquarius_location_tag',
            },
        ),
        migrations.CreateModel(
            name='LocationFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='internal.locationfolder')),
            ],
            options={
                'verbose_name': 'Location Folder',
                'verbose_name_plural': 'Location Folders',
                'db_table': 'internal_aquarius_location_folder',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uniqueId', models.CharField(help_text='Unique ID for the location, e.g., UUID or similar', max_length=52, primary_key=True, serialize=False, unique=True)),
                ('identifier', models.CharField(help_text='Unique identifier for the location', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lastModified', models.DateTimeField(help_text='Last modified timestamp')),
                ('type', models.CharField(help_text='Type of the location', max_length=50)),
                ('elevation', models.FloatField(blank=True, help_text='Elevation of the location in meters', null=True)),
                ('elevationUnit', models.CharField(default='m', help_text="Unit of elevation, e.g., 'm' for meters", max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location', srid=4326)),
                ('primaryFolder', models.ForeignKey(blank=True, help_text='Primary folder for the location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder', to='internal.locationfolder')),
                ('notes', models.ManyToManyField(blank=True, help_text='Notes associated with the location', related_name='notes', to='internal.locationnote')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the location', related_name='tags', to='internal.locationtag')),
            ],
            options={
                'verbose_name': 'Aquarius Location',
                'verbose_name_plural': 'Aquarius Locations',
                'db_table': 'internal_aquarius_location',
            },
        ),
    ]
