# Generated by Django 4.2 on 2023-11-09 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaN',
            fields=[
                ('stat_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('source', models.TextField(blank=True, null=True)),
                ('operator', models.TextField(blank=True, null=True)),
                ('cn', models.TextField(blank=True, null=True)),
                ('hoehe', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asgii_station_meta',
            },
        ),
    ]
