# Generated by Django 5.0.2 on 2024-12-19 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaP',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_real', models.BooleanField()),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('raw_from', models.DateTimeField(blank=True, null=True)),
                ('raw_until', models.DateTimeField(blank=True, null=True)),
                ('filled_from', models.DateTimeField(blank=True, null=True)),
                ('filled_until', models.DateTimeField(blank=True, null=True)),
                ('richter_class', models.TextField(blank=True, null=True)),
                ('qc_dropped', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meta_p',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MetaN',
        ),
    ]
