# Generated by Django 5.0.2 on 2024-03-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_bw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sribwpolygons',
            old_name='sri_id',
            new_name='grid_id',
        ),
        migrations.AddField(
            model_name='sribwdata',
            name='grid_id',
            field=models.ForeignKey(db_column='grid_id', default=555, help_text='ID to link to the Grid-Cell', on_delete=django.db.models.deletion.DO_NOTHING, to='sri_bw.sribwpolygons'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql="UPDATE sri_bw_data SET grid_id = sri_id;",
            reverse_sql="UPDATE sri_bw_data SET sri_id = grid_id;"),
        migrations.AlterUniqueTogether(
            name='sribwdata',
            unique_together={('grid_id', 'event_rank')},
        ),
        migrations.RemoveField(
            model_name='sribwdata',
            name='sri_id',
        ),
    ]
