# Generated by Django 5.0.2 on 2024-03-27 09:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sri_bw', '0003_create_sri_max_events'),
    ]

    operations = [
        migrations.RunSQL(
            """SELECT UpdateGeometrySRID('sri_bw_polygons', 'geometry', 3857);
            UPDATE sri_bw_polygons SET geometry=ST_Transform(ST_setSRID(geometry, 4326), 3857);""",
            """SELECT UpdateGeometrySRID('sri_bw_polygons', 'geometry', 4326);
            UPDATE sri_bw_polygons SET geometry=ST_Transform(ST_setSRID(geometry, 3857), 4326);""")
    ]
